{% set python_min = "3.10" %}
{% set name = "gliderpy" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gliderpy-{{ version }}.tar.gz
  sha256: 94f93156f533b46d725ca175a762b936d713b9d86456f09b741db92ece7ce570

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - erddapy
    - gsw
    - httpx
    - pandas
    - pandas-flavor
    - xarray

test:
  imports:
    - gliderpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ioos/gliderpy
  summary: Glider Data Fetcher
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - callumrollo
    - ocefpaf
