{% set name = "gliderpy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gliderpy-{{ version }}.tar.gz
  sha256: dfdf45d920c567062265080f3051a953e0bf063babe8f94ecd33a7a298a44213

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.8
    - erddapy
    - httpx
    - pandas
    - xarray

test:
  imports:
    - gliderpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ioos/gliderpy
  summary: Glider Data Fetcher
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - callumrollo
    - ocefpaf
