{% set name = "gliderpy" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gliderpy-{{ version }}.tar.gz
  sha256: a77313770a4f963a8e8ccb1a6540f3b2ad15ce82ad649037b3aa8611023e4aac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
    - pip
  run:
    - python >=3.10
    - erddapy
    - httpx
    - pandas
    - xarray

test:
  imports:
    - gliderpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ioos/gliderpy
  summary: Glider Data Fetcher
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - callumrollo
    - ocefpaf
